#!/bin/bash
# shellcheck disable=SC2086


log_enter $DIR_DTS$DIR_TEMPLATE$DIR_TMPL$CMD_INIT

source $DIR_DTS$DIR_TEMPLATE$DIR_TMPL$DIR_DCKR$CMD_INIT
source $DIR_DTS$DIR_TEMPLATE$DIR_TMPL$DIR_ENV$CMD_INIT

log_exit $DIR_DTS$DIR_TEMPLATE$DIR_TMPL$CMD_INIT