@echo off


CALL LOG_ENTER pENV

call sENV
if exist project\pENV_MOD (
  call project\pENV_MOD
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%REACT_CONT%"
SET "PROJ_CONT_DATA_DIR=%REACT_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%REACT_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%REACT_CONT_HOME_DIR%"
SET "PROJ_HOST_DIR=%REACT_HOST_DIR%"
SET "PROJ_IMG=%REACT_IMG%"
SET "PROJ_PORT_INT=%REACT_PORT_INT%"
SET "PROJ_VOL=%REACT_VOL%"
SET "PROJ_VOL_DIR=%REACT_VOL_DIR%"

CALL LOG_EXIT pENV

