@echo off


CALL LOG_ENTER pENV

call sENV
if exist project\pENV_MOD (
  call project\pENV_MOD
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%MS_ADMIN_CONT%"
SET "PROJ_CONT_DATA_DIR=%MS_ADMIN_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%MS_ADMIN_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%MS_ADMIN_CONT_HOME_DIR%"
SET "PROJ_HOST_DIR=%MS_ADMIN_HOST_DIR%"
SET "PROJ_IMG=%MS_ADMIN_IMG%"
SET "PROJ_PORT_INT=%MS_ADMIN_PORT_INT%"
SET "PROJ_VOL=%MS_ADMIN_VOL%"
SET "PROJ_VOL_DIR=%MS_ADMIN_VOL_DIR%"


CALL LOG_EXIT pENV

