#!/bin/bash
# shellcheck disable=SC2086


log_enter pENV

source sENV.sh
if [ -f "project/pENV_MOD.sh" ]; then
  source project/pENV_MOD.sh
fi



export PROJ_LABEL=$SYS_NAME
export PROJ_NET=$SYS_NET

export PROJ_CONT=$JAVA_CONT
export PROJ_CONT_DATA_DIR=$JAVA_DATA_DIR
export PROJ_CONT_DIR=$JAVA_CONT_DIR
export PROJ_CONT_HOME_DIR=$JAVA_CONT_HOME_DIR
export PROJ_HOST_DIR=$JAVA_HOST_DIR
export PROJ_IMG=$JAVA_IMG
export PROJ_PORT_INT=$JAVA_PORT_INT
export PROJ_VOL=$JAVA_VOL
export PROJ_VOL_DIR=$JAVA_VOL_DIR

export PROJ_PORT_EXT_ADMIN=$JAVA_PORT_EXT_ADMIN
export PROJ_PORT_EXT_APPS=$JAVA_PORT_EXT_APPS
export PROJ_PORT_EXT_DBG=$JAVA_PORT_EXT_DBG

log_exit pENV