#!/bin/bash
# shellcheck disable=SC2086


log_enter pENV_MOD

source sENV.sh


export PROJ_HOST=$JAVA_HOST
export PROJ_PASSWORD=$JAVA_PASSWORD
export PROJ_PORT_EXT=$JAVA_PORT_EXT
export PROJ_USER=$JAVA_USER

export PROJ_PORT_INT_ADMIN=$JAVA_PORT_INT_ADMIN
export PROJ_PORT_INT_APPS=$JAVA_PORT_INT_APPS
export PROJ_PORT_INT_DBG=$JAVA_PORT_INT_DBG

log_exit pENV_MOD