@echo off


CALL LOG_ENTER pGO

CALL project\pENV

SET "CONT=%PROJ_CONT%"
SET "CONT_DIR=%PROJ_CONT_DIR%"
SET "CONT_MNT_DIR=%PROJ_CONT_MNT_DIR%"
SET "HOST=%PROJ_HOST%"
SET "HOST_DIR=%CD%%PROJ_HOST_DIR%"
SET "HOST_MNT_DIR=%CD%%PROJ_HOST_MNT_DIR%"
SET "IMG=%PROJ_IMG%"
SET "LABEL=%PROJ_LABEL%"
SET "MODE=%PROJ_MODE%"
SET "NET=%PROJ_NET%"
SET "PASSWORD=%PROJ_PASSWORD%"
SET "PORT_EXT=%PROJ_PORT_EXT%"
SET "PORT_INT=%PROJ_PORT_INT%"
SET "USER=%PROJ_USER%"

SET "ART=%PROJ_ART%"
SET "FILE=%PROJ_FILE%"
SET "GRP=%PROJ_GRP%"
SET "PKG=%PROJ_PKG%"
SET "REPO_HOST=%PROJ_REPO_HOST%"
SET "REPO_IP=%PROJ_REPO_IP%"
SET "REPO_PORT_EXT=%PROJ_REPO_PORT_EXT%"
SET "VER=%PROJ_VER%"

SET "DB_ADDR=%PROJ_DB_ADDR%"
SET "DB_DATABASE=%PROJ_DB_DATABASE%"
SET "DB_PASSWORD=%PROJ_DB_PASSWORD%"
SET "DB_USER=%PROJ_DB_USER%"
SET "DB_VENDOR=%PROJ_DB_VENDOR%"
SET "DBG=%PROJ_DBG%"
SET "DBG_PORT=%PROJ_DBG_PORT%"
SET "IMPORT=%PROJ_IMPORT%"
SET "LOG_LEVEL=%PROJ_LOG_LEVEL%"
SET "PORT_EXT_ADMIN=%PROJ_PORT_EXT_ADMIN%"
SET "PORT_INT_ADMIN=%PROJ_PORT_INT_ADMIN%"
SET "PROXY_FORWARD=%PROJ_PROXY_FORWARD%"
SET "ROOT_LOG_LEVEL=%PROJ_ROOT_LOG_LEVEL%"

call LOG_VAR CONT %CONT%
call LOG_VAR CONT_DIR %CONT_DIR%
call LOG_VAR CONT_MNT_DIR %CONT_MNT_DIR%
call LOG_VAR HOST %HOST%
call LOG_VAR HOST_DIR %HOST_DIR%
call LOG_VAR HOST_MNT_DIR %HOST_MNT_DIR%
call LOG_VAR IMG %IMG%
call LOG_VAR LABEL %LABEL%
call LOG_VAR MODE %MODE%
call LOG_VAR NET %NET%
call LOG_VAR PASSWORD %PASSWORD%
call LOG_VAR PORT_EXT %PORT_EXT%
call LOG_VAR PORT_INT %PORT_INT%
call LOG_VAR USER %USER%

call LOG_VAR ART %ART%
call LOG_VAR FILE %FILE%
call LOG_VAR GRP %GRP%
call LOG_VAR PKG %PKG%
call LOG_VAR REPO_HOST %REPO_HOST%
call LOG_VAR REPO_IP %REPO_IP%
call LOG_VAR REPO_PORT_EXT %REPO_PORT_EXT%
call LOG_VAR VER VER%

call LOG_VAR DB_ADDR %DB_ADDR%
call LOG_VAR DB_DATABASE %DB_DATABASE%
call LOG_VAR DB_PASSWORD %DB_PASSWORD%
call LOG_VAR DB_USER %DB_USER%
call LOG_VAR DB_VENDOR %DB_VENDOR%
call LOG_VAR DBG %DBG%
call LOG_VAR DBG_PORT %DBG_PORT%
call LOG_VAR IMPORT %IMPORT%
call LOG_VAR LOG_LEVEL %LOG_LEVEL%
call LOG_VAR PORT_EXT_ADMIN %PORT_EXT_ADMIN%
call LOG_VAR PORT_INT_ADMIN %PORT_INT_ADMIN%
call LOG_VAR PROXY_FORWARD %PROXY_FORWARD%
call LOG_VAR ROOT_LOG_LEVEL %ROOT_LOG_LEVEL%

docker run ^
       -%MODE% ^
       -p %HOST%:%PORT_EXT%:%PORT_INT% ^
       -p %HOST:%PORT_EXT_ADMIN%:%PORT_INT_ADMIN% ^
       -v %HOST_DIR%:%CONT_DIR% ^
       -e ART=%ART% ^
       -e FILE=%FILE% ^
       -e GRP=%GRP% ^
       -e PKG=%PKG% ^
       -e REPO_HOST=%REPO_HOST% ^
       -e REPO_PORT_EXT=%REPO_PORT_EXT% ^
       -e VER=%VER% ^
       -e DB_DATABASE=%DB_DATABASE% ^
       -e DB_PASSWORD=%DB_PASSWORD% ^
       -e DB_USER=%DB_USER% ^
       -e DB_VENDOR=%DB_VENDOR% ^
       -e DEBUG=%DBG% ^
       -e DEBUG_PORT=%DBG_PORT% ^
       -e KEYCLOAK_IMPORT=%IMPORT% ^
       -e KEYCLOAK_LOGLEVEL=%LOG_LEVEL% ^
       -e KEYCLOAK_PASSWORD=%PASSWORD% ^
       -e KEYCLOAK_USER=%USER% ^
       -e PROXY_ADDRESS_FORWARDING=%PROXY_FORWARD% ^
       -e ROOT_LOGLEVEL=%ROOT_LOG_LEVEL% ^
       --add-host=%REPO_HOST%:%REPO_IP% ^
       --label=%LABEL% ^
       --mount type=bind,src=%HOST_MNT_DIR%,target=%CONT_MNT_DIR% ^
       --name=%CONT% ^
       --network=%NET% ^
       %IMG%

call LOG_EXIT pGO

