@echo off


CALL LOG_ENTER pENV

CALL tENV

SET "PROJ_HOST=%SMTP_HOST%"
SET "PROJ_IP=%SMTP_IP%"
SET "PROJ_PASSWORD=%SMTP_PASSWORD%"
SET "PROJ_PORT_EXT=%SMTP_PORT_EXT%"
SET "PROJ_USER=%SMTP_USER%"

SET "PROJ_SH_ADDRESS=%SMTP_SH_ADDRESS%"
SET "PROJ_SH_ALIASES=%SMTP_SH_ALIASES%"
SET "PROJ_SH_PORT=%SMTP_SH_PORT%"

CALL LOG_EXIT pENV

