@echo off


CALL LOG_ENTER pENV

CALL tENV

SET "PROJ_HOST=%SMTP_HOST%"
SET "PROJ_HOST_IP=%SMTP_HOST_IP%"
SET "PROJ_PASSWORD=%SMTP_PASSWORD%"
SET "PROJ_PORT_EXT=%SMTP_PORT_EXT%"
SET "PROJ_USER=%SMTP_USER%"

SET "PROJ_ALIASES=%SMTP_ALIASES%"

CALL LOG_EXIT pENV

