#!/bin/bash
# shellcheck disable=SC2086


log_env_enter pENV


export PROJ_HOST=$SOAP_CLNT_HOST
export PROJ_PASSWORD=$SOAP_CLNT_PASSWORD
export PROJ_PORT_EXT=$SOAP_CLNT_PORT_EXT
export PROJ_USER=$SOAP_CLNT_USER

export PROJ_ART=$SOAP_CLNT_ART
export PROJ_FILE=$SOAP_CLNT_FILE
export PROJ_GRP=$SOAP_CLNT_GRP
export PROJ_REPO_HOST=$NEXUS3_HOST
export PROJ_REPO_IP=$NEXUS3_IP
export PROJ_REPO_PORT_EXT=$NEXUS3_PORT_EXT
export PROJ_VER=$SOAP_CLNT_VER

log_env_enter pENV