@echo off


CALL LOG_ENTER tENV

CALL sENV

SET "PROJ_HOST=%WP_HOST%"
SET "PROJ_PASSWORD=%WP_PASSWORD%"
SET "PROJ_PORT_EXT=%WP_PORT_EXT%"
SET "PROJ_USER=%WP_USER%"

SET "PROJ_DB_HOST=%MS_CONT%"
SET "PROJ_DB_NAME=%MS_NAME%"
SET "PROJ_DB_PASSWORD=%MS_PASSWORD%"
SET "PROJ_DB_USER=%MS_USER%"

SET "PROJ_TABLE_PREFIX=%WP_TABLE_PREFIX%"

CALL LOG_EXIT pENV

