@echo off


CALL LOG_ENTER pENV_MOD

CALL sENV

SET "PROJ_HOST=%MVN_LIB_HOST%"
SET "PROJ_PASSWORD=%MVN_LIB_PASSWORD%"
SET "PROJ_PORT_EXT=%MVN_LIB_PORT_EXT%"
SET "PROJ_USER=%MVN_LIB_USER%"

CALL LOG_EXIT pENV_MOD

