@echo off


CALL LOG_ENTER pENV

call sENV
if exist project\pENV_MOD (
  call project\pENV_MOD
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%MVN_LIB_CONT%"
SET "PROJ_CONT_DATA_DIR=%MVN_LIB_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%MVN_LIB_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%MVN_LIB_CONT_HOME_DIR%"
SET "PROJ_HOST_DIR=%MVN_LIB_HOST_DIR%"
SET "PROJ_IMG=%MVN_LIB_IMG%"
SET "PROJ_PORT_INT=%MVN_LIB_PORT_INT%"
SET "PROJ_VOL=%MVN_LIB_VOL%"
SET "PROJ_VOL_DIR=%MVN_LIB_VOL_DIR%"


CALL LOG_EXIT pENV

