@echo off


CALL LOG_ENTER pENV

call sENV
if exist project\pENV (
  call project\pENV
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%SWAG_GEN_CONT%"
SET "PROJ_CONT_DIR=%SWAG_GEN_CONT_DIR%"
SET "PROJ_CONT_MNT_DIR=%SWAG_GEN_CONT_MNT_DIR%"
SET "PROJ_HOST_DIR=%SWAG_GEN_HOST_DIR%"
SET "PROJ_HOST_MNT_DIR=%SWAG_HOST_MNT_DIR%"
SET "PROJ_IMG=%SWAG_GEN_IMG%"
SET "PROJ_PORT_INT=%SWAG_GEN_PORT_INT%"


CALL LOG_EXIT pENV

