@echo off

call %DIR_BIN%%DIR_SLASH%LOG_ENTER %TMPL_DIR%%DCKR_DIR%%DIR_SLASH%%FILE_INIT%

xcopy /q /y %TMPL_DIR%%DCKR_DIR%%FILES% %DIR_BIN% >NUL

call LOG_EXIT %TMPL_DIR%%DCKR_DIR%%DIR_SLASH%%FILE_INIT%