@echo off


CALL %DIR_BIN%%DIR_SLASH%LOG_ENTER pENV

CALL tENV

SET "PROJ_HOST=%SWAG_CG_CLI_HOST%"
SET "PROJ_PASSWORD=SWAG_CG_CLI_PASSWORD%"
SET "PROJ_PORT_EXT=%SWAG_CG_CLI_PORT_EXT%"
SET "PROJ_USER=%SWAG_CG_CLI_USER%"

SET "PROJ_FILE=%SWAG_CG_CLI_FILE%"

CALL LOG_EXIT pENV

