@echo off


call LOG_ENTER %DIR_GLBL%%DIR_SLASH%%FILE_INIT%

CALL %DIR_GLBL%\docker_compose%DIR_SLASH%%FILE_INIT%
CALL %DIR_GLBL%\docker_global%DIR_SLASH%%FILE_INIT%
CALL %DIR_GLBL%\docker_project%DIR_SLASH%%FILE_INIT%
CALL %DIR_GLBL%\docker_system%DIR_SLASH%%FILE_INIT%
CALL %DIR_GLBL%%ENV_DIR%%DIR_SLASH%%FILE_INIT%
CALL %DIR_GLBL%%GIT_DIR%%DIR_SLASH%%FILE_INIT%
CALL %DIR_GLBL%\kube%DIR_SLASH%%FILE_INIT%
CALL %DIR_GLBL%\openshift%DIR_SLASH%%FILE_INIT%

call LOG_EXIT %DIR_GLBL%%DIR_SLASH%%FILE_INIT%
