@echo off


call LOG_ENTER %DIR_GLBL%%CMD_INIT%

CALL %DIR_GLBL%\docker_compose%CMD_INIT%
CALL %DIR_GLBL%\docker_global%CMD_INIT%
CALL %DIR_GLBL%\docker_project%CMD_INIT%
CALL %DIR_GLBL%\docker_system%CMD_INIT%
CALL %DIR_GLBL%%ENV_DIR%%CMD_INIT%
CALL %DIR_GLBL%%GIT_DIR%%CMD_INIT%
CALL %DIR_GLBL%\kube%CMD_INIT%
CALL %DIR_GLBL%\openshift%CMD_INIT%

call LOG_EXIT %DIR_GLBL%%CMD_INIT%
