@echo off


call LOG_ENTER %DIR_GLBL%\%FILE_INIT%

CALL %DIR_GLBL%\docker_compose\%FILE_INIT%
CALL %DIR_GLBL%\docker_global\%FILE_INIT%
CALL %DIR_GLBL%\docker_project\%FILE_INIT%
CALL %DIR_GLBL%\docker_system\%FILE_INIT%
CALL %DIR_GLBL%%ENV_DIR%\%FILE_INIT%
CALL %DIR_GLBL%%GIT_DIR%\%FILE_INIT%
CALL %DIR_GLBL%\kube\%FILE_INIT%
CALL %DIR_GLBL%\openshift\%FILE_INIT%

call LOG_EXIT %DIR_GLBL%\%FILE_INIT%
