#!/bin/bash
# shellcheck disable=SC2086

BASE=base
BIN=bin
BNDL=bundler
DOT=.
ENV=env
EXT=sh
OS=linux
SLASH=/

CMD_LOG=$SLASH"LOG"$DOT$EXT

DIR_BASE=$SLASH$BASE
DIR_BIN=$SLASH$BIN
DIR_BNDL=$SLASH$BNDL
DIR_ENV=$SLASH$ENV
DIR_OS=$SLASH$OS

source $DIR_DTS$DIR_BASE$DIR_BNDL$DIR_ENV$CMD_INIT
source .$DIR_BIN/bENV.sh
echo DIR_LOG is $DIR_LOG
echo DIR_OS is $DIR_OS
source $BNDL_DIR$DIR_LOG$DIR_OS$CMD_LOG
sleep 10
log_enter $DIR_DTS$CMD_INIT

source $DIR_DTS$DIR_BASE$CMD_INIT
source $DIR_DTS$DIR_TEMPLATE$CMD_INIT

log_exit $DIR_DTS$CMD_INIT

