@echo off

SET "BASE=base"
SET "BIN=bin"
SET "BNDL=bndl"
SET "DOT=."
SET "ENV=env"
SET "EXT="
SET "OS=win"
SET "SLASH=\"

SET "CMD_LOG=%SLASH%"LOG"%DOT%%EXT%"

SET "BASE_DIR=%SLASH%%BASE%"
SET "BIN_DIR=%BIN%"
SET "BNDL_DIR=%SLASH%%BNDL%"
SET "ENV_DIR=%SLASH%%ENV%"
SET "OS_DIR=%SLASH%%OS%"

CALL %DIR_DTS%%BASE_DIR%%BNDL_DIR%%ENV_DIR%%CMD_INIT%
CALL %BIN_DIR%/bENV
CALL %DIR_BNDL%%LOG_DIR%%OS_DIR%%CMD_LOG%

CALL LOG_LOAD %DIR_DTS%%CMD_INIT%

CALL %DIR_BASE%%CMD_INIT%
CALL %DIR_TMPL_CURR%%CMD_INIT%
CALL %DIR_SYS%%CMD_INIT%

CALL LOG_LOAD %DIR_DTS%%CMD_INIT%