@echo off


echo dts\init.cmd [ENTER]

SET "BASE=base"
SET "BIN=bin"
SET "BNDL=bndl"
SET "DOT=."
SET "ENV=env"
SET "EXT="
SET "OS=win"
SET "PROJ=proj"
SET "SLASH=\"
SET "STAR=*"
SET "UPDATE=update"

SET "CMD_INIT=%SLASH%"init"%DOT%%EXT%"
SET "CMD_LOG=%SLASH%"LOG"%DOT%%EXT%"

SET DIR_SLASH=%SLASH%

SET "BASE_DIR=%DIR_SLASH%%BASE%"
SET "BIN_DIR=%BIN%"
SET "BNDL_DIR=%DIR_SLASH%%BNDL%"
SET "ENV_DIR=%DIR_SLASH%%ENV%"
SET "OS_DIR=%DIR_SLASH%%OS%"
SET "PROJ_DIR=%DIR_SLASH%%PROJ%"


SET "DIR_BASE=%DTS_DIR%%BASE_DIR%
:: ECHO DIR_BASE is %DIR_BASE% [INFO]

SET "DIR_BIN=%BIN_DIR%
:: ECHO DIR_BIN is %DIR_BIN% [INFO]

SET "DIR_BNDL=%DIR_BASE%%BNDL_DIR%
:: ECHO DIR_BNDL is %DIR_BNDL% [INFO]

SET "DIR_ENV=%DIR_BNDL%%ENV_DIR%
:: ECHO DIR_BNDL is %DIR_BNDL% [INFO]

SET "DIR_PROJ=%DIR_BASE%%PROJ_DIR%
:: ECHO DIR_PROJ is %DIR_PROJ% [INFO]

SET "FILE_LOG=%DIR_BNDL%%LOG_DIR%%OS_DIR%%CMD_LOG%
:: ECHO FILE_LOG is %FILE_LOG% [INFO]

SET "FILES=%OS_DIR%%DIR_SLASH%%STAR%%DOT%%EXT%"
:: ECHO FILES is %FILES% [INFO]

IF NOT EXIST %DIR_BIN% (
  mkdir -p %DIR_BIN%
  :: ECHO bin created [INFO]
)

CALL %DIR_ENV%%CMD_INIT%
CALL %DIR_BIN%/bENV
CALL %FILE_LOG%
CALL LOG_LOAD %DIR_DTS%%CMD_INIT%

CALL %DIR_BASE%%CMD_INIT%
CALL %DIR_TMPL_CURR%%CMD_INIT%
CALL %DIR_SYS%%CMD_INIT%

CALL %DIR_BIN%%DIR_SLASH%"mSET_PATH"
CALL pINIT

CALL LOG_LOAD %DIR_DTS%%CMD_INIT%