@echo off

SET "BNDL=bundler"
SET "DOT=."
SET "DCKR=docker"
SET "ENV=env"
SET "EXT=sh"
SET "GIT=git"
SET "GLOBAL=global"
SET "LOG=log"
SET "MISC=misc"
SET "OS=linux"

SET "CMD_LOG=$SLASH"LOG"$DOT$EXT"

SET "DIR_BNDL=$SLASH$BNDL"
SET "DIR_DCKR=$SLASH$DCKR"
SET "DIR_ENV=$SLASH$ENV"
SET "DIR_GIT=$SLASH$GIT"
SET "DIR_GLOBAL=$SLASH$GLOBAL"
SET "DIR_LOG=$SLASH$LOG"
SET "DIR_MISC=$SLASH$MISC"
SET "DIR_OS=$SLASH$OS"
SET "DIR_TMPL=$SLASH$TMPL_NAME"


CALL %DIR_BNDL%\log\win\LOG_LOAD %CMD_DIR%%CMD_INIT%

CALL %CMD_DIR%%DIR_BASE%%CMD_INIT%
CALL %CMD_DIR%%DIR_TMPL%%CMD_INIT%

CALL %DIR_BNDL%\log\win\LOG_UNLOAD %CMD_DIR%%CMD_INIT%