#!/bin/bash
# shellcheck disable=SC2086

BASE=base
BIN=bin
BNDL=bndl
DOT=.
ENV=env
EXT=sh
OS=linux
SLASH=/

CMD_INIT=$SLASH"init"$DOT$EXT
CMD_LOG=$SLASH"LOG"$DOT$EXT

BASE_DIR=$SLASH$BASE
BIN_DIR=$BIN
BNDL_DIR=$SLASH$BNDL
ENV_DIR=$SLASH$ENV
OS_DIR=$SLASH$OS

DIR_ENV=$DIR_DTS$BASE_DIR$BNDL_DIR$ENV_DIR
echo DIR_ENV is $DIR_ENV [VAR]

echo DIR_BIN is $DIR_BIN [VAR]
if [ ! -d $DIR_BIN ]; then
  mkdir $DIR_BIN
  echo create $DIR_BIN
fi

source $DIR_ENV$CMD_INIT
source $BIN_DIR/bENV.sh
source $DIR_BNDL$LOG_DIR$OS_DIR$CMD_LOG

log_enter $DIR_DTS$CMD_INIT

source $DIR_BASE$CMD_INIT
source $DIR_TMPL_CURR$CMD_INIT
source $DIR_SYS$CMD_INIT

source $DIR_BIN$DIR_SLASHmSET_PATH.sh
source pINIT.sh
pINIT

log_exit $DIR_DTS$CMD_INIT

