@echo off


CALL LOG_ENTER pENV

CALL tENV

SET "PROJ_HOST=%NEXUS3_HOST%"
SET "PROJ_PASSWORD=%NEXUS3_PASSWORD%"
SET "PROJ_PORT_EXT=%NEXUS3_PORT_EXT%"
SET "PROJ_USER=%NEXUS3_USER%"

SET "PROJ_CONT_PATH=%NEXUS3_CONT_PATH%"
SET "PROJ_JAVA_OPTS=%NEXUS3_JAVA_OPTS%"
SET "PROJ_LAUNCH_CONF=%NEXUS3_LAUNCH_CONF%"
SET "PROJ_MAX_HEAP=%NEXUS3_MAX_HEAP%"
SET "PROJ_MIN_HEAP=%NEXUS3_MIN_HEAP%"

CALL LOG_EXIT pENV_MOD

