@echo off


CALL %DIR_BNDL%\log%OS_DIR%\LOG_LOAD \%DIR_BNDL%%MISC_DIR%%CMD_INIT%

xcopy /q /y %DIR_BNDL%%MISC_DIR%%OS_DIR%\*.cmd %DIR_BIN% > NUL

CALL %DIR_BNDL%\log%OS_DIR%\LOG_UNLOAD \%DIR_BNDL%%MISC_DIR%%CMD_INIT%
