@echo off


CALL %DIR_BIN%%DIR_SLASH%LOG_ENTER tENV

call sENV
if exist project\pENV (
  call project\pENV
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%NET_CONT%"
SET "PROJ_CONT_DATA_DIR=%NET_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%NET_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%NET_CONT_HOME_DIR%"
SET "PROJ_HOST_DIR=%NET_HOST_DIR%"
SET "PROJ_IMG=%NET_IMG%"
SET "PROJ_PORT_INT=%NET_PORT_INT%"
SET "PROJ_VOL=%NET_VOL%"

CALL LOG_EXIT tENV
