@echo off


call LOG_ENTER pENV

call sENV
if exist project\pENV_MOD (
  call project\pENV_MOD
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%NET_CONT%"
SET "PROJ_CONT_DATA_DIR=%NET_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%NET_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%NET_CONT_HOME_DIR%"
SET "PROJ_HOST_DIR=%NET_HOST_DIR%"
SET "PROJ_IMG=%NET_IMG%"
SET "PROJ_PORT_INT=%NET_PORT_INT%"
SET "PROJ_VOL=%NET_VOL%"
SET "PROJ_VOL_DIR=%NET_VOL_DIR%"

call LOG_EXIT pENV
