#!/bin/bash
# shellcheck disable=SC2086


log_enter $DIR_DTS$DIR_TEMPLATE$DIR_TMPL$DCKR_DIR$CMD_INIT

cp $DIR_DTS$DIR_TEMPLATE$DIR_TMPL$DIR_DCKR$$DIR_OS/*.sh .$DIR_BIN

log_exit $DIR_DTS$DIR_TEMPLATE$DIR_TMPL$DCKR_DIR$CMD_INIT