@echo off


CALL LOG_ENTER %DIR_DTS%%DIR_TEMPLATE%%DIR_TMPL%%DIR_DCKR%%CMD_INIT%

xcopy /q /y %DIR_DTS%%DIR_TEMPLATE%%DIR_TMPL%%DIR_DCKR%%DIR_OS\*.cmd .%DIR_BIN% >NUL

CALL LOG_EXIT %DIR_DTS%%DIR_TEMPLATE%%DIR_TMPL%%DIR_DCKR%%CMD_INIT%
