#!/bin/bash
# shellcheck disable=SC2086

echo bENV_DIRS [ENTER]

source settings.sh
source bENV_NAMES.sh
source bENV_TKNS.sh


export DIR_BASE=$FOR_SLASH$BASE
export DIR_BNDL=$FOR_SLASH$BNDL
export DIR_GIT=$SLASH$GIT
export DIR_GLBL=$SLASH$GLBL
export DIR_LOG=$SLASH$LOG
export DIR_MISC=$SLASH$MISC
export DIR_OS=$SLASH$OS
export DIR_SYS=$SLASH$SYS
export DIR_TMPL=$SLASH$TMPL_NAME
export DIR_TMPL_CUR=$SLASH$TMPL_NAME

export BSE_DIR=$DIR_DTS$DIR_BASE
export BNDL_DIR=$BSE_DIR$DIR_BNDL
export GLBL_DIR=$BSE_DIR$DIR_GLBL
export SYS_DIR=$UP$UP$DIR_SYS
export TMPL_DIR=$DIR_DTS$DIR_TMPL$DIR_TMPL_CUR

echo DIR_LOG is $DIR_LOG
echo DIR_OS is $DIR_OS

echo bENV_DIRS [EXIT]
