#!/bin/bash
# shellcheck disable=SC2086

log_enter gENV_DIRS

source settings.sh

source gENV_CATS.sh
source gENV_NAMES.sh
source gENV_TKNS.sh

export ANCH_DIR=$FOR_SLASH$ANCH
export API_DIR=$FOR_SLASH$API
export APP_DIR=$FOR_SLASH$APP
export BASE_DIR=$DIR_SLASH$BASE
export BIN_DIR=$BIN
export BNDL_DIR=$DIR_SLASH$BNDL
export CA_CERT_DIR=$FOR_SLASH$CA_CERT
export CA_TRUST_DIR=$FOR_SLASH$CA_TRUST
export CODE_DIR=$FOR_SLASH$CODE
export CONTENT_DIR=$FOR_SLASH$CONTENT
export DATA_DIR=$FOR_SLASH$DATA
export DBG_DIR=$FOR_SLASH$DBG
export DCKR_DIR=$DIR_SLASH$DCKR
export DPLY_DIR=$FOR_SLASH$DEPLOY
export ENV_DIR=$DIR_SLASH$ENV
export ETC_DIR=$FOR_SLASH$ETC
export EXTRA_DIR=$FOR_SLASH$EXTRA
export GEN_DIR=$FOR_SLASH$GEN
export GIS_DIR=$FOR_SLASH$GIS
export GITT_DIR=$DIR_SLASH$GIT
export GLBL_DIR=$DIR_SLASH$GLBL
export GO_DIR=$FOR_SLASH$GO
export GRDL_DIR=$FOR_SLASH$GRDL
export HME_DIR=$FOR_SLASH$HME
export HTML_DIR=$FOR_SLASH$HTML
export JBOSS_DIR=$FOR_SLASH$JBOSS
export KEYCLOAK_DIR=$FOR_SLASH$KEYCLOAK
export LIB_DIR=$FOR_SLASH$LIB
export LINUX_DIR=$FOR_SLASH$LINUX
export LOCAL_DIR=$FOR_SLASH$LOCAL
export LOG_DIR=$DIR_SLASH$LOG
export MISC_DIR=$DIR_SLASH$MISC
export M2_DIR=$FOR_SLASH$M2
export MS_DIR=$FOR_SLASH$MS
export MVN_DIR=$FOR_SLASH$MVN
export MYSQL_DIR=$FOR_SLASH$MYSQL
export NANO_DIR=$FOR_SLASH$NANO
export NEXUS_DATA_DIR=$FOR_SLASH$NEXUS$DASH$DATA
export NGINX_DIR=$FOR_SLASH$NGINX
export NODE_DIR=$FOR_SLASH$NODE
export OA_DIR=$FOR_SLASH$OA
export OS_DIR=$DIR_SLASH$OS
export OPT_DIR=$FOR_SLASH$OPT
export PG_ADMIN_DIR=$FOR_SLASH$PG$SPLIT$ADMIN
export PG_DIR=$FOR_SLASH$PG
export PKI_DIR=$FOR_SLASH$PKI
export PROJ_DIR=$FOR_SLASH$DIR_PROJ
export REACT_DIR=$FOR_SLASH$REACT
export RUN_DIR=$FOR_SLASH$RUN
export SHARE_DIR=$FOR_SLASH$SHARE
export SNGL_DIR=$FOR_SLASH$SHARE
export SOAP_DIR=$FOR_SLASH$SOAP
export SOURCE_DIR=$FOR_SLASH$SOURCE
export SPECS_DIR=$FOR_SLASH$SPECS
export SRC_DIR=$FOR_SLASH$SRC
export SYS_DIR=$DIR_SLASH$SYS
export SWAG_DIR=$FOR_SLASH$SWAG
export TMPL_DIR=$DIR_SLASH$TMPL
export THEMES_DIR=$FOR_SLASH$THEMES
export TMP_DIR=$FOR_SLASH$TMP
export TRGT_DIR=$FOR_SLASH$TRGT
export USR_DIR=$FOR_SLASH$USR
export VAR_DIR=$FOR_SLASH$VAR
export WF_DIR=$FOR_SLASH$WF
export WIN_DIR=$FOR_SLASH$WIN
export WP_DIR=$FOR_SLASH$WP
export WWW_DIR=$FOR_SLASH$WWW

export WP_CONTENT_DIR=$WP_DIR$DASH$CONTENT



log_exit gENV_DIRS
