#!/bin/bash
# shellcheck disable=SC2086

log_env_enter tENV

source sENV.sh

log_env_var FILE_ENV_PROJ $FILE_ENV_PROJ

if [ -f $FILE_ENV_PROJ ]; then
  source $FILE_ENV_PROJ
fi


export PROJ_LABEL=$SYS_NAME
export PROJ_NET=$SYS_NET

export PROJ_CONT=$SOAP_CLNT_CONT
export PROJ_CONT_DIR=$SOAP_CLNT_CONT_DIR
export PROJ_CONT_MNT_DIR=$SOAP_CLNT_CONT_MNT_DIR
export PROJ_HOST_DIR=$SOAP_CLNT_HOST_DIR
export PROJ_HOST_MNT_DIR=$SOAP_CLNT_HOST_MNT_DIR
export PROJ_IMG=$SOAP_CLNT_IMG
export PROJ_PORT_INT=$SOAP_CLNT_PORT_INT
export PROJ_VOL=$SOAP_CLNT_VOL

log_env_exit tENV