@echo off


CALL LOG_ENTER pENV_MOD

CALL sENV

SET "PROJ_HOST=%JAVA_HOST%"
SET "PROJ_PASSWORD=%JAVA_PASSWORD%"
SET "PROJ_PORT_EXT=%JAVA_PORT_EXT%"
SET "PROJ_USER=%JAVA_USER%"

SET "PROJ_PORT_EXT_ADMIN=%JAVA_PORT_EXT_ADMIN%"
SET "PROJ_PORT_EXT_APPS=%JAVA_PORT_EXT_APPS%"
SET "PROJ_PORT_EXT_DBG=%JAVA_PORT_EXT_DBG%"

CALL LOG_EXIT pENV_MOD

