@echo off


CALL LOG_ENTER pGO

CALL pENV

SET "CONT=%PROJ_CONT%"
SET "CONT_DIR=%PROJ_CONT_DIR%"
SET "HOST=%PROJ_HOST%"
SET "HOST_DIR=%CD%%PROJ_HOST_DIR%"
SET "IMG=%PROJ_IMG%"
SET "LABEL=%PROJ_LABEL%"
SET "MODE=%PROJ_MODE%"
SET "NET=%PROJ_NET%"
SET "PASSWORD=%PROJ_PASSWORD%"
SET "PORT_EXT=%PROJ_PORT_EXT%"
SET "PORT_INT=%PROJ_PORT_INT%"
SET "USER=%PROJ_USER%"
SET "VOL=%PROJ_VOL%"
SET "VOL_DIR=%PROJ_VOL_DIR%"

call LOG_VAR CONT %CONT%
call LOG_VAR CONT_DIR is %CONT_DIR%
call LOG_VAR HOST is %HOST%
call LOG_VAR HOST_DIR is %HOST_DIR%
call LOG_VAR IMG is %IMG%
call LOG_VAR LABEL is %LABEL%
call LOG_VAR NET is %NET%
call LOG_VAR PASSWORD is %PASSWORD%
call LOG_VAR PORT_EXT is %PORT_EXT%
call LOG_VAR PORT_INT is %PORT_INT%
call LOG_VAR USER is %USER%
call LOG_VAR VOL is %VOL%
call LOG_VAR VOL_DIR is %VOL_DIR%


docker run ^
       -%MODE% ^
       -v %CONT_DIR%:%HOST_DIR% ^
       --label=%LABEL% ^
       --name=%CONT% ^
       %IMG%

call LOG_EXIT pGO

