@echo off


CALL LOG_ENTER pGO

CALL pENV

SET "CONT=%PROJ_CONT%"
SET "CONT_DIR=%PROJ_CONT_DIR%"
SET "CONT_MNT_DIR=%PROJ_CONT_MNT_DIR%"
SET "HOST=%PROJ_HOST%"
SET "HOST_DIR=%CD%%PROJ_HOST_DIR%"
SET "HOST_MNT_DIR=%CD%%PROJ_HOST_MNT_DIR%"
SET "IMG=%PROJ_IMG%"
SET "LABEL=%PROJ_LABEL%"
SET "MODE=%PROJ_MODE%"
SET "NET=%PROJ_NET%"
SET "PASSWORD=%PROJ_PASSWORD%"
SET "PORT_EXT=%PROJ_PORT_EXT%"
SET "PORT_INT=%PROJ_PORT_INT%"
SET "USER=%PROJ_USER%"

SET "ART=%PROJ_ART%"
SET "GRP=%PROJ_GRP%"
SET "REPO_URL=%PROJ_REPO_URL%"
SET "REPO_PORT=%PROJ_REPO_PORT%"
SET "VER=%PROJ_VER%"

SET "DB_ADDR=%PROJ_DB_ADDR%"
SET "DB_DATABASE=%PROJ_DB_DATABASE%"
SET "DB_PASSWORD=%PROJ_DB_PASSWORD%"
SET "DB_USER=%PROJ_DB_USER%"
SET "DB_VENDOR=%PROJ_DB_VENDOR%"
SET "DBG=%PROJ_DBG%"
SET "DBG_PORT=%PROJ_DBG_PORT%"

CALL LOG_VAR CONT %CONT%
CALL LOG_VAR CONT_DIR %CONT_DIR%
CALL LOG_VAR CONT_MNT_DIR %CONT_MNT_DIR%
CALL LOG_VAR HOST %HOST%
CALL LOG_VAR HOST_DIR %HOST_DIR%
CALL LOG_VAR HOST_MNT_DIR %HOST_MNT_DIR%
CALL LOG_VAR IMG %IMG%
CALL LOG_VAR LABEL %LABEL%
CALL LOG_VAR MODE %MODE%
CALL LOG_VAR NET %NET%
CALL LOG_VAR PASSWORD %PASSWORD%
CALL LOG_VAR PORT_EXT %PORT_EXT%
CALL LOG_VAR PORT_INT %PORT_INT%
CALL LOG_VAR USER %USER%
CALL LOG_VAR VOL %VOL%

CALL LOG_VAR ART %ART%
CALL LOG_VAR GRP %GRP%
CALL LOG_VAR REPO_URL %REPO_URL%
CALL LOG_VAR REPO_PORT %REPO_PORT%
CALL LOG_VAR VER %VER%

CALL LOG_VAR DB_ADDR %DB_ADDR%
CALL LOG_VAR DB_DATABASE %DB_DATABASE%
CALL LOG_VAR DB_PASSWORD %DB_PASSWORD%
CALL LOG_VAR DB_USER %DB_USER%
CALL LOG_VAR DB_VENDOR %DB_VENDOR%
CALL LOG_VAR DBG %DBG%

docker run ^
       -%MODE% ^
       -p %HOST%:%PORT_EXT%:%PORT_INT% ^
       -p %HOST:%PORT_EXT_ADMIN%:%PORT_INT_ADMIN% ^
       -v %HOST_DIR%:%CONT_DIR% ^
       -e ART=%ART% ^
       -e FILE=%FILE% ^
       -e GRP=%GRP% ^
       -e REPO_URL=%REPO_URL% ^
       -e REPO_PORT=%REPO_PORT% ^
       -e VER=%VER% ^
       -e DB_ADDR=%DB_ADDR% ^
       -e DB_DATABASE=%DB_DATABASE% ^
       -e DB_PASSWORD=%DB_PASSWORD% ^
       -e DB_USER=%DB_USER% ^
       -e DB_VENDOR=%DB_VENDOR% ^
       --label=%LABEL% ^
       --name=%CONT% ^
       --network=%NET% ^
       %IMG%

CALL LOG_EXIT pGO

REM       --mount type=bind,src=%HOST_MNT_DIR%,target=%CONT_MNT_DIR% ^

