@echo off


call %DIR_BIN%%DIR_SLASH%LOG_ENTER %DIR_GLBL%%GIT_DIR%%DIR_SLASH%%FILE_INIT%

xcopy /q /y %DIR_GLBL%%GIT_DIR%%FILES% %DIR_BIN% >NUL

call LOG_EXIT %DIR_GLBL%%GIT_DIR%%DIR_SLASH%%FILE_INIT%
