@echo off


rem call %DIR_BIN%%DIR_SLASH%LOG_ENTER %DIR_GLBL%%GIT_DIR%%DIR_SLASH%%FILE_INIT%
rem echo %DIR_GLBL%%DIR_SLASH%git%DIR_SLASH%%FILE_INIT% [ENTER]

xcopy /q /y %DIR_GLBL%%DIR_SLASH%git%FILES% %DIR_BIN% >NUL

rem call LOG_EXIT %DIR_GLBL%%GIT_DIR%%DIR_SLASH%%FILE_INIT%
rem echo %DIR_GLBL%%DIR_SLASH%git%DIR_SLASH%%FILE_INIT% [EXIT]
