@echo off


rem CALL %DIR_BIN%%DIR_SLASH%LOG_ENTER %DIR_TMPL%%FILE_INIT%
rem echo %DIR_TMPL%%FILE_INIT% [ENTER]

SET "CMD_DCKR=%DIR_TMPL_CURR%%DCKR_DIR%FILE_INIT%"
rem echo CMD_DCKR is %CMD_DCKR%
CALL %CMD_DCKR%

SET "CMD_ENV=%DIR_TMPL_CURR%%ENV_DIR%FILE_INIT%"
rem echo CMD_ENV is %CMD_ENV%
CALL %CMD_ENV%

SET "CMD_SYS=%DIR_TMPL_CURR%%SYS_DIR%FILE_INIT%"
rem echo CMD_SYS is %CMD_SYS%
CALL %CMD_SYS%


rem CALL LOG_EXIT \%DIR_TMPL%%FILE_INIT%
rem echo %DIR_TMPL%%FILE_INIT% [EXIT]
