#!/bin/bash
# shellcheck disable=SC2086


log_enter pENV


export PROJ_HOST=$NEXUS3_HOST
export PROJ_PASSWORD=$NEXUS3_PASSWORD
export PROJ_PORT_EXT=$NEXUS3_PORT_EXT
export PROJ_USER=$NEXUS3_USER

export PROJ_CONT_PATH=$NEXUS3_CONT_PATH
export PROJ_JAVA_OPTS=${NEXUS3_JAVA_OPTS}
export PROJ_LAUNCH_CONF=$NEXUS3_LAUNCH_CONF
export PROJ_MAX_HEAP=$NEXUS3_MAX_HEAP
export PROJ_MIN_HEAP=$NEXUS3_MIN_HEAP

log_exit pENV_MOD