#!/bin/bash
# shellcheck disable=SC2086


log_enter $DIR_DTS$DIR_BASE$DIR_GLOBAL$CMD_INIT

source $DIR_DTS$DIR_BASE$DIR_GLOBAL/docker_compose$CMD_INIT
source $DIR_DTS$DIR_BASE$DIR_GLOBAL/docker_global$CMD_INIT
source $DIR_DTS$DIR_BASE$DIR_GLOBAL/docker_project$CMD_INIT
source $DIR_DTS$DIR_BASE$DIR_GLOBAL/docker_system$CMD_INIT
source $DIR_DTS$DIR_BASE$DIR_GLOBAL/env$CMD_INIT
source $DIR_DTS$DIR_BASE$DIR_GLOBAL/git$CMD_INIT
source $DIR_DTS$DIR_BASE$DIR_GLOBAL/kube$CMD_INITv
source $DIR_DTS$DIR_BASE$DIR_GLOBAL/openshift$CMD_INIT

log_exit $DIR_DTS$DIR_BASE$DIR_GLOBAL$CMD_INIT