#!/bin/bash
# shellcheck disable=SC2086


log_enter tENV

source sENV.sh
if [ -f "project/pENV_MOD.sh" ]; then
  source project/pENV_MOD.sh
fi



export PROJ_LABEL=$SYS_NAME
export PROJ_NET=$SYS_NET

export PROJ_REPO_HOST=$NEXUS_CONT
export PROJ_REPO_PASSWORD=$NEXUS_PASSWORD
export PROJ_REPO_PORT=$NEXUS_PORT_EXT
export PROJ_REPO_USER=$NEXUS_USER

export PROJ_CONT=$GRDL_LIB_CONT
export PROJ_DATA_DIR=$GRDL_LIB_CONT_DATA_DIR
export PROJ_CONT_DIR=$GRDL_LIB_CONT_DIR
export PROJ_CONT_HOME_DIR=$GRDL_LIB_CONT_HOME_DIR
export PROJ_HOST_DIR=$GRDL_LIB_HOST_DIR
export PROJ_IMG=$GRDL_LIB_IMG
export PROJ_PORT_INT=$GRDL_LIB_PORT_INT
export PROJ_VOL=$GRDL_LIB_VOL
export PROJ_VOL_DIR=$GRDL_LIB_VOL_DIR

log_exit pENV