@echo off


CALL LOG_ENTER pENV_MOD

CALL sENV

SET "PROJ_HOST=%NODE_HOST%"
SET "PROJ_PASSWORD=%NODE_PASSWORD%"
SET "PROJ_PORT_EXT=%NODE_PORT_EXT%"
SET "PROJ_USER=%NODE_USER%"

SET "PROJ_LOG_LEVEL=%NODE_LOG_LEVEL%"

CALL LOG_EXIT pENV_MOD

