@echo off


CALL LOG_ENTER pENV

call sENV
if exist project\pENV (
  call project\pENV
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%PG_CONT%"
SET "PROJ_CONT_DIR=%PG_CONT_DIR%"
SET "PROJ_CONT_MNT_DIR=%PG_CONT_MNT_DIR%"
SET "PROJ_HOST_DIR=%PG_HOST_DIR%"
SET "PROJ_HOST_MNT_DIR=%PG_HOST_MNT_DIR%"
SET "PROJ_IMG=%PG_IMG%"
SET "PROJ_PORT_INT=%PG_PORT_INT%"
SET "PROJ_VOL=%PG_VOL%"

CALL LOG_EXIT pENV

