@echo off


CALL %DIR_BIN%%DIR_SLASH%LOG_ENTER \%DIR_TMPL%%DIR_SLASH%%FILE_INIT%

CALL %DIR_TMPL%\docker%DIR_SLASH%%FILE_INIT%
CALL %DIR_TMPL%%ENV_DIR%%DIR_SLASH%%FILE_INIT%

CALL LOG_EXIT \%DIR_TMPL%%DIR_SLASH%%FILE_INIT%