#!/bin/bash
# shellcheck disable=SC2086


log_enter $DIR_CMD$FILE_INIT

source $DIR_CMD$DIR_COMPOSE$FILE_INIT
source $DIR_CMD$DIR_GLBL$FILE_INIT
source $DIR_CMD$DIR_PROJ$FILE_INIT
source $DIR_CMD$DIR_SYS$FILE_INIT
source $DIR_CMD$DIR_GITT$FILE_INIT
source $DIR_CMD$DIR_KUBE$FILE_INIT
source $DIR_CMD$DIR_OS$FILE_INIT

log_exit $DIR_CMD$FILE_INIT

