#!/bin/bash
# shellcheck disable=SC2086


log_enter $DIR_CMD$FILE_INIT

source $DIR_CMD$COMPOSE_DIR$FILE_INIT
source $DIR_CMD$GITT_DIR$FILE_INIT
source $DIR_CMD$GLBL_DIR$FILE_INIT
source $DIR_CMD$KUBE_DIR$FILE_INIT
source $DIR_CMD$MISC_DIR$FILE_INIT
source $DIR_CMD$OPENSHIFT_DIR$FILE_INIT
log_var PROJ_DIR $PROJ_DIR
source $DIR_CMD$PROJ_DIR$FILE_INIT
source $DIR_CMD$SYS_DIR$FILE_INIT

log_exit $DIR_CMD$FILE_INIT

