FROM openjdk:11-jdk-buster

RUN apt install -y default-jre

USER container
ENV  USER=container HOME=/home/container

WORKDIR /home/container

COPY ./code/entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
