@echo off


CALL LOG_ENTER pENV

CALL tENV

SET "PROJ_HOST=%API_HOST%"
SET "PROJ_PASSWORD=%API_PASSWORD%"
SET "PROJ_PORT_EXT=%API_PORT_EXT%"
SET "PROJ_USER=%API_USER%"

SET "PROJ_ART=%API_ART%"
SET "PROJ_FILE=%API_FILE%"
SET "PROJ_GRP=%API_GRP%"
SET "PROJ_REPO_URL=%NEXUS3_HOST%"
SET "PROJ_REPO_PORT=%NEXUS3_PORT_EXT%"
SET "PROJ_VER=%API_VER%"


CALL LOG_EXIT pENV_MOD

