FROM maven:3.6.3-jdk-8

USER root

EXPOSE 8080
EXPOSE 9990

ARG CONT_DIR
ARG HOST_DIR
ARG SYS_DIR
ARG TMPL_DIR

ARG CERT_DIR
ARG REPO_HOST
ARG REPO_PORT_EXT

RUN echo CONT_DIR is ${CONT_DIR}
RUN echo HOST_DIR is ${HOST_DIR}
RUN echo SYS_DIR is ${SYS_DIR}
RUN echo TMPL_DIR is ${TMPL_DIR}

RUN echo CERT_DIR is ${CERT_DIR}
RUN echo REPO_HOST is ${REPO_HOST}
RUN echo REPO_PORT_EXT is ${REPO_PORT_EXT}

RUN mkdir -p ${CONT_DIR}

WORKDIR ${CONT_DIR}

RUN mkdir -p /root/.m2
COPY ${SYS_DIR}/settings.xml /root/.m2/settings.xml

RUN mkdir -p ${CERT_DIR}

COPY ${SYS_DIR}/nexus.crt ${CERT_DIR}
RUN update-ca-certificates -v

# copy the project files
COPY ./code .

# build all dependencies for offline use
RUN mvn dependency:go-offline -B

ENV REPO_HOST $REPO_HOST
ENV REPO_PORT_EXT $REPO_PORT_EXT

RUN echo REPO_HOST is ${REPO_HOST}
RUN echo REPO_PORT_EXT is ${REPO_PORT_EXT}

ENTRYPOINT ["mvn", "package"]

#ENTRYPOINT ["/bin/sh"]
