@echo off


CALL LOG_ENTER pENV

CALL sENV

SET "PROJ_HOST=%MS_ADMIN_HOST%"
SET "PROJ_PASSWORD=%MS_ADMIN_PASSWORD%"
SET "PROJ_PORT_EXT=%MS_ADMIN_PORT_EXT%"
SET "PROJ_USER=%MS_ADMIN_USER%"

SET "PROJ_DB_HOST=%$MS_HOST%"
SET "PROJ_DB_PORT=%$MS_PORT_EXT%"

CALL LOG_EXIT pENV_MOD

