#!/bin/bash
# shellcheck disable=SC2086


log_enter $DIR_DTS$DIR_BASE$DIR_BUNDLER$CMD_INIT

source $DIR_DTS$DIR_BASE$DIR_BUNDLER$DIR_ENV$CMD_INIT
source $DIR_DTS$DIR_BASE$DIR_BUNDLER$DIR_GIT$CMD_INIT
source $DIR_DTS$DIR_BASE$DIR_BUNDLER$DIR_LOG$CMD_INIT
source $DIR_DTS$DIR_BASE$DIR_BUNDLER$DIR_MISC$CMD_INIT

log_exit $DIR_DTS$DIR_BASE$DIR_BUNDLER$CMD_INIT

