#!/bin/bash
# shellcheck disable=SC2086


log_enter $DIR_DTS$DIR_BASE$DIR_BUNDLER$CMD_INIT

source $DIR_DTS$DIR_BASE$DIR_BUNDLER/env$CMD_INIT
source $DIR_DTS$DIR_BASE$DIR_BUNDLER/git$CMD_INIT
source $DIR_DTS$DIR_BASE$DIR_BUNDLER/log$CMD_INIT
source $DIR_DTS$DIR_BASE$DIR_BUNDLER/misc$CMD_INIT

log_exit $DIR_DTS$DIR_BASE$DIR_BUNDLER$CMD_INIT

