@echo off


call LOG_ENTER gENV_NAMES

REM These values may not be changed.  Technologies depend on these

SET "ADMIN=admin"
SET "API=api"
SET "APP=app"
SET "CA_CERT=ca-certificates"
SET "CLI=cli"
SET "CODE=Code"
SET "CONTENT=content"
SET "DATA=data"
SET "DCKR=docker"
SET "DPLY=deployment"
SET "FILE=file"
SET "GIT=git"
SET "GLOBAL=global"
SET "GRDL=gradle"
SET "HME=home"
SET "HTML=html"
SET "HTTP=http"
SET "JBOSS=jboss"
SET "JSON=json"
SET "KEYCLOAK=keycloak"
SET "LIB=lib"
SET "LINUX=linux"
SET "LOCAL=local"
SET "M2=.m2"
SET "MVN=maven"
SET "MYSQL=mysql"
SET "NEXUS=nexus"
SET "NGINX=nginx"
SET "NODE=node"
SET "OPT=opt"
SET "RUN=run"
SET "SHARE=share"
SET "SNGL=standalone"
SET "SOCK=sock"
SET "SPECS=specs"
SET "SRC=src"
SET "SYSTEM=system"
SET "THEMES=themes"
SET "TMP=tmp"
SET "TMPL=tmpl"
SET "TRGT=target"
SET "USR=usr"
SET "VAR=var"
SET "WIN=win"
SET "WWW=www"

call LOG_EXIT gENV_NAMES

