#!/bin/bash
# shellcheck disable=SC2086


log_enter $DIR_TMPL_CURR$SYS_DIR$FILE_INIT

CMD_MVN=$DIR_SYS$MVN_DIR$FILE_INIT
log_var CMD_MVN $CMD_MVN
source $CMD_MVN

CMD_NEX=$DIR_SYS$NEXUS_DIR$FILE_INIT
log_var CMD_NEX $CMD_NEX
source $CMD_NEX

SRC_CLNT=$DIR_SYS$SOAP_DIR$DIR_SLASH$PROJ_NAME$DIR_SLASH$CLNT$DIR_SLASH$STAR
log_var SRC_CLNT $SRC_CLNT

TRG_CLNT=$CODE$DIR_SLASH$GEN
log_var TRG_CLNT $TRG_CLNT

cp $SRC_CLNT $TRG_CLNT

SRC_SRVR=$DIR_SYS$API_DIR$DIR_SLASH$PROJ_NAME$DIR_SLASH$SRVR$DIR_SLASH$STAR
log_var SRC_SRVR $SRC_SRVR

TRG_SRVR=$CODE$DIR_SLASH$GEN
log_var TRG_SRVR $TRG_SRVRv

cp $SRC_SRVR $TRG_SRVR

log_exit $DIR_TMPL_CURR$SYS_DIR$FILE_INIT