@echo off


CALL LOG_LOAD mSET_PATH

CALL %DIR_BNDL%%LOG_DIR%%OS_DIR%\LOG_VAR PATH %PATH%

SET "FIND=%CD%\bin"
CALL %DIR_BNDL%%LOG_DIR%%OS_DIR%\LOG_VAR FIND %FIND%

ECHO "%PATH%" | findstr /C:"%FIND%">nul && (
  CALL LOG_DUP PATH
  GOTO :EOF
)

SET "PATH=%PATH%;%CD%\bin"
ECHO SET "PATH=%PATH%;%CD%\bin" >path.cmd


:EOF

CALL LOG_UNLOAD mSET_PATH

EXIT /B %ERRORLEVEL%

