FROM python

USER root

EXPOSE 5432

ARG CONT_DIR

RUN mkdir -p ${CONT_DIR}
WORKDIR ${CONT_DIR}

copy code/requirement.txt

RUN pip install --no-cache-dir -r requiremnt.txt

copy code .

CMD [ "python", "./your-daemon-or-script.py" ]