@echo off


CALL LOG_ENTER pINSTALL


CALL project\pENV

CALL LOG_ENTER DIR_SYS %DIR_SYS%
CALL LOG_ENTER PROJ_NAME %PROJ_NAME%
CALL LOG_ENTER
CALL LOG_ENTER SYS_NAME %SYS_NAME%

SET "SOURCE=./%DIR_SYS%/api/%PROJ_NAME%"
SET "TARGET=code/"

CALL LOG_ENTER TARGET %TARGET%
CALL LOG_ENTER SOURCE %SOURCE%%

mkdir -p %TARGET%
xcopy /q /y %SOURCE%/* %TARGET%

CALL LOG_EXIT pINSTALL

