@echo off


CALL %DIR_BIN%%DIR_SLASH%LOG_ENTER pINSTALL


CALL project\pENV

CALL LOG_VAR DIR_SYS %DIR_SYS%
CALL LOG_VAR PROJ_NAME %PROJ_NAME%
CALL LOG_VAR
CALL LOG_VAR SYS_NAME %SYS_NAME%

SET "SOURCE=./%DIR_SYS%/api/%PROJ_NAME%"
SET "TARGET=code/"

CALL LOG_VAR TARGET %TARGET%
CALL LOG_VAR SOURCE %SOURCE%%

mkdir -p %TARGET%
xcopy /q /y %SOURCE%/* %TARGET%

CALL LOG_EXIT pINSTALL

