@echo off


CALL %DIR_BNDL%\log%OS_DIR%\LOG_LOAD \%DIR_BNDL%%GIT_DIR%%CMD_INIT%

xcopy /q /y %DIR_BNDL%%GIT_DIR%%FILES% %DIR_BIN% >NUL

CALL %DIR_BNDL%\log%OS_DIR%\LOG_UNLOAD \%DIR_BNDL%%GIT_DIR%%CMD_INIT%

