@echo off


CALL %DIR_BIN%%DIR_SLASH%LOG_ENTER tENV

call sENV
if exist project\pENV (
  call project\pENV
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%WSDL_CONT%"
SET "PROJ_CONT_DIR=%WSDL_CONT_DIR%"
SET "PROJ_CONT_MNT_DIR=%WSDL_CONT_MNT_DIR%"
SET "PROJ_HOST_DIR=%WSDL_HOST_DIR%"
SET "PROJ_HOST_MNT_DIR=%WSDL_HOST_MNT_DIR%"
SET "PROJ_IMG=%WSDL_IMG%"
SET "PROJ_PORT_INT=%WSDL_PORT_INT%"
SET "PROJ_VOL=%WSDL_VOL%"

SET "PROJ_CONT_CERT_DIR=%WSDL_CONT_CERT_DIR%

CALL LOG_EXIT tENV
