#!/bin/bash
# shellcheck disable=SC2086



# echo $DIR_DTS$BASE_DIR$BNDL_DIR$ENV_DIR$CMD_INIT [ENTER]

cp $DIR_DTS$BASE_DIR$BNDL_DIR$ENV_DIR$OS_DIR/*.sh $DIR_BIN

# echo $DIR_DTS$BASE_DIR$BNDL_DIR$ENV_DIR$CMD_INIT [EXIT]
