@echo off


CALL %DIR_BNDL%\log%OS_DIR%\LOG_LOAD \%DIR_BNDL%%ENV_DIR%%CMD_INIT%

xcopy /q /y %DIR_BNDL%%ENV_DIR%%OS_DIR%\*.cmd %DIR_BIN% >NUL

CALL %DIR_BNDL%\log%OS_DIR%\LOG_UNLOAD \%DIR_BNDL%%ENV_DIR%%CMD_INIT%
