#!/bin/bash
# shellcheck disable=SC2086



echo $DIR_DTS$DIR_BASE$DIR_BNDL$DIR_ENV$CMD_INIT [ENTER]

cp $DIR_DTS$DIR_BASE$DIR_BNDL$DIR_ENV$DIR_OS/*.sh .$DIR_BIN

echo $DIR_DTS$DIR_BASE$DIR_BNDL$DIR_ENV$CMD_INIT [EXIT]
