@echo off


CALL LOG_ENTER pENV

CALL tENV

SET "PROJ_HOST=%SOAP_HOST%"
SET "PROJ_PASSWORD=%SOAP_PASSWORD%"
SET "PROJ_PORT_EXT=%SOAP_PORT_EXT%"
SET "PROJ_USER=%SOAP_USER%"

SET "PROJ_PORT_EXT_ADMIN=%TS_PORT_EXT_ADMIN%"
SET "PROJ_PORT_EXT_APPS=%TS_PORT_EXT_APPS%"
SET "PROJ_PORT_EXT_DBG=%TS_PORT_EXT_DBG%"


CALL LOG_EXIT pENV

