@echo off


CALL LOG_ENTER pENV

call sENV
if exist project\pENV (
  call project\pENV
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%JAVA_CONT%"
SET "PROJ_CONT_DATA_DIR=%JAVA_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%JAVA_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%JAVA_CONT_HOME_DIR%"
SET "PROJ_HOST_DIR=%JAVA_HOST_DIR%"
SET "PROJ_IMG=%JAVA_IMG%"
SET "PROJ_PORT_INT=%JAVA_PORT_INT%"
SET "PROJ_VOL=%JAVA_VOL%"
SET "PROJ_VOL_DIR=%JAVA_VOL_DIR%"

SET "PROJ_PORT_INT_ADMIN=%WF_PORT_INT_ADMIN%"
SET "PROJ_PORT_INT_APPS=%WF_PORT_INT_APPS%"
SET "PROJ_PORT_INT_DBG=%WF_PORT_INT_DBG%"


CALL LOG_EXIT pENV

