@echo off


CALL LOG_ENTER pENV

call sENV
if exist project\pENV_MOD (
  call project\pENV_MOD
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%NEXUS3_CONT%"
SET "PROJ_CONT_DATA_DIR=%NEXUS3_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%NEXUS3_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%NEXUS3_CONT_HOME_DIR%"
SET "PROJ_HOST_DIR=%NEXUS3_HOST_DIR%"
SET "PROJ_IMG=%NEXUS3_IMG%"
SET "PROJ_PORT_INT=%NEXUS3_PORT_INT%"
SET "PROJ_VOL=%NEXUS3_VOL%"
SET "PROJ_VOL_DIR=%NEXUS3_VOL_DIR%"


CALL LOG_EXIT pENV

