@echo off


CALL LOG_ENTER tENV

call sENV
if exist project\pENV_MOD (
  call project\pENV_MOD
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%JFROG_CONT%"
SET "PROJ_CONT_DATA_DIR=%JFROG_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%JFROG_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%JFROG_CONT_HOME_DIR%"
SET "PROJ_HOST_DIR=%JFROG_HOST_DIR%"
SET "PROJ_IMG=%JFROG_IMG%"
SET "PROJ_PORT_INT=%JFROG_PORT_INT%"
SET "PROJ_VOL=%JFROG_VOL%"
SET "PROJ_VOL_DIR=%JFROG_VOL_DIR%"

SET "PROJ_PORT_INT_ADMIN=%JFROG_PORT_INT_ADMIN%"
SET "PROJ_PORT_INT_DBG=%JFROG_PORT_INT_DBG%"



call LOG_EXIT pENV
