@echo off



rem CALL LOG_LOAD %DIR_BASE%%DIR_SLASH%%FILE_INIT%
rem echo %DIR_BASE%%DIR_SLASH%%FILE_INIT% [ENTER]

SET "CMD_GLBL=%DIR_GLBL%%DIR_SLASH%%FILE_INIT%"
rem echo CMD_GLBL is %CMD_GLBL%

CALL %CMD_GLBL%

SET "CMD_TMPL=%DIR_TMPL%%DIR_SLASH%%FILE_INIT%"
rem echo CMD_TMPL is %CMD_TMPL%

CALL %CMD_TMPL%

xcopy /q /y %DIR_PROJ%%DIR_SLASH%%FILE_INIT% . >NUL


rem CALL LOG_UNLOAD %DIR_BASE%%DIR_SLASH%%FILE_INIT%
rem echo %DIR_BASE%%DIR_SLASH%%FILE_INIT% [EXIT]
