#!/bin/bash
# shellcheck disable=SC2086

CMD_DIR=$DIR_DTS$DIR_BASE

log_enter $CMD_DIR$CMD_INIT

source $CMD_DIR$DIR_BUNDLER$CMD_INIT
#source $CMD_DIR$DIR_GLOBAL$CMD_INIT
#source $CMD_DIR$DIR_TEMPLATE$CMD_INIT
#source $CMD_DIR$DIR_PROJECT$CMD_INIT

log_exit $DIR_DTS$DIR_BASE$CMD_INIT

