#!/bin/bash
# shellcheck disable=SC2086


DIR=$DIR_DTS$DIR_BASE

log_enter $DIR_DTS$DIR_BASE$CMD_INIT

source $DIR_DTS$DIR_BASE$DIR_BUNDLER$CMD_INIT
#source $DIR_DTS$DIR_BASE$DIR_GLOBAL$CMD_INIT
#source $DIR$DIR_TEMPLATE$CMD_INIT
#source $DIR$DIR_PROJECT$CMD_INIT

log_exit $DIR_DTS$DIR_BASE$CMD_INIT

