@echo off


echo bENV_DIRS [ENTER]

CALL settings
CALL bin/bENV_NAMES
CALL bin/bENV_TKNS


SET "BASE_DIR=%BCK_SLASH%%BASE%"
SET "BNDL_DIR=%BCK_SLASH%%BNDL%"
SET "DCKR_DIR=%BCK_SLASH%%DCKR%"
SET "ENV_DIR=%BCK_SLASH%%ENV%"
SET "GIT_DIR=%BCK_SLASH%%GIT%"
SET "GLBL_DIR=%BCK_SLASH%%GLBL%"
SET "LOG_DIR=%BCK_SLASH%%LOG%"
SET "MISC_DIR=%BCK_SLASH%%MISC%"
SET "OS_DIR=%BCK_SLASH%%OS%"
SET "SYS_DIR=%BCK_SLASH%%SYS%"
SET "TMPL_DIR=%BCK_SLASH%%TMPL%"
SET "TMPL_CURR_DIR=%BCK_SLASH%%TMPL_NAME%"

echo bENV_DIRS [EXIT]
