@echo off


CALL LOG_ENTER pENV

call sENV
if exist project\pENV_MOD (
  call project\pENV_MOD
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%NEXUS_CONT%"
SET "PROJ_CONT_DIR=%NEXUS_CONT_DIR%"
SET "PROJ_CONT_MNT_DIR=%NEXUS_CONT_MNT_DIR%"
SET "PROJ_HOST_DIR=%NEXUS_HOST_DIR%"
SET "PROJ_HOST_MNT_DIR=%NEXUS_HOST_MNT_DIR%"
SET "PROJ_IMG=%NEXUS_IMG%"
SET "PROJ_PORT_INT=%NEXUS_PORT_INT%"


CALL LOG_EXIT pENV

