@echo off


rem CALL %DIR_BIN%%DIR_SLASH%LOG_ENTER \%DIR_TMPL%\docker%DIR_SLASH%%FILE_INIT%
echo %DIR_TMPL%%DIR_SLASH%docker%DIR_SLASH%%FILE_INIT% [ENTER]

xcopy /q /y %DIR_TMPL%\docker%FILES% %DIR_BIN% >NUL

rem CALL LOG_EXIT \%DIR_TMPL%\docker%DIR_SLASH%%FILE_INIT%
echo %DIR_TMPL%%DIR_SLASH%docker%DIR_SLASH%%FILE_INIT% [EXIT]
