@echo off


CALL LOG_ENTER pENV

call sENV
if exist project\pENV (
  call project\pENV
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%VOLUME_CONT%"
SET "PROJ_CONT_DATA_DIR=%VOLUME_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%VOLUME_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%VOLUME_CONT_HOME_DIR%"
SET "PROJ_HOST_DIR=%VOLUME_HOST_DIR%"
SET "PROJ_IMG=%VOLUME_IMG%"
SET "PROJ_PORT_INT=%VOLUME_PORT_INT%"
SET "PROJ_VOL=%VOLUME_VOL%"
SET "PROJ_VOL_DIR=%VOLUME_VOL_DIR%"


CALL LOG_EXIT pENV

