@echo off


REM echo bENV_DIRS [ENTER]

CALL settings
CALL bin/bENV_NAMES
CALL bin/bENV_TKNS


SET "BASE_DIR=\%BASE%"
SET "BNDL_DIR=\%BNDL%"
SET "BIN_DIR=%BIN%"
SET "DCKR_DIR=\%DCKR%"
SET "ENV_DIR=\%ENV%"
SET "GIT_DIR=\%GIT%"
SET "GLBL_DIR=\%GLBL%"
SET "LOG_DIR=\%LOG%"
SET "MISC_DIR=\%MISC%"
SET "OS_DIR=\%OS%"
SET "SYS_DIR=\%SYS%"
SET "TMPL_DIR=\%TMPL%"
SET "TMPL_CURR_DIR=\%TMPL_NAME%"

REM echo bENV_DIRS [EXIT]
