@echo off


REM echo bENV_DIRS [ENTER]

CALL settings
CALL bin/bENV_NAMES
CALL bin/bENV_TKNS


SET "BASE_DIR=%DIR_SLASH%%BASE%"
SET "BNDL_DIR=%DIR_SLASH%%BNDL%"
SET "BIN_DIR=%BIN%"
SET "DCKR_DIR=%DIR_SLASH%%DCKR%"
SET "ENV_DIR=%DIR_SLASH%%ENV%"
SET "GLBL_DIR=%DIR_SLASH%%GLBL%"
SET "LOG_DIR=%DIR_SLASH%%LOG%"
SET "MISC_DIR=%DIR_SLASH%%MISC%"
SET "OS_DIR=%DIR_SLASH%%OS%"
SET "SYS_DIR=%DIR_SLASH%%SYS%"
SET "TMPL_DIR=%DIR_SLASH%%TMPL%"
SET "TMPL_CURR_DIR=%DIR_SLASH%%TMPL_NAME%"

SET "DIR_BASE=%DIR_DTS%%BASE_DIR%"
 echo DIR_BASE is %DIR_BASE%

SET "DIR_BIN=%BIN_DIR%"
 echo DIR_BIN is %DIR_BIN%

SET "DIR_BNDL=%DIR_BASE%%BNDL_DIR%"
 echo DIR_BNDL is %DIR_BASE%

SET "DIR_GLBL=%DIR_BASE%%GLBL_DIR%"
 echo DIR_GLBL is %DIR_GLBL%

SET "DIR_SYS=%UP%%UP%%SYS%"
 echo DIR_SYS is %DIR_SYS%

SET "DIR_TMPL=%DIR_DTS%%TMPL_DIR%"
 echo TMPL_DIR is %TMPL_DIR%

SET "DIR_TMPL_CURR=%DIR_TMPL%%TMPL_CURR_DIR%"
 echo DIR_TMPL_CURR is %DIR_TMPL_CURR%

REM echo bENV_DIRS [EXIT]
