@echo off


rem call LOG_ENTER pGO
echo pGO [ENTER]

CALL project\pENV

SET "CONT=%PROJ_CONT%"
SET "CONT_DIR=%PROJ_CONT_DIR%"
SET "CONT_MNT_DIR=%PROJ_CONT_MNT_DIR%"
SET "HOST=%PROJ_HOST%"
SET "HOST_DIR=%CD%%PROJ_HOST_DIR%"
SET "HOST_MNT_DIR=%CD%%PROJ_HOST_MNT_DIR%"
SET "IMG=%PROJ_IMG%"
SET "LABEL=%PROJ_LABEL%"
SET "MODE=%PROJ_MODE%"
SET "NET=%PROJ_NET%"
SET "PASSWORD=%PROJ_PASSWORD%"
SET "PORT_EXT=%PROJ_PORT_EXT%"
SET "PORT_INT=%PROJ_PORT_INT%"
SET "USER=%PROJ_USER%"
SET "VOL=%PROJ_VOL%"


rem CALL LOG_VAR CONT %CONT%
rem CALL LOG_VAR CONT_DIR %CONT_DIR%
rem CALL LOG_VAR CONT_MNT_DIR %CONT_MNT_DIR%
rem CALL LOG_VAR HOST %HOST%
rem CALL LOG_VAR HOST_DIR %HOST_DIR%
rem CALL LOG_VAR HOST_MNT_DIR %HOST_MNT_DIR%
rem CALL LOG_VAR IMG %IMG%
rem CALL LOG_VAR LABEL %LABEL%
rem CALL LOG_VAR MODE %MODE%
rem CALL LOG_VAR NET %NET%
rem CALL LOG_VAR PASSWORD %PASSWORD%
rem CALL LOG_VAR PORT_EXT %PORT_EXT%
rem CALL LOG_VAR PORT_INT %PORT_INT%
rem CALL LOG_VAR USER %USER%
rem CALL LOG_VAR VOL %VOL%

mkdir -p %HOST_MNT_DIR%

docker run ^
       -%MODE% ^
       -p %HOST%:%PORT_EXT%:%PORT_INT% ^
       --label=%LABEL% ^
       --mount type=bind,src=%VOL%,dst=%CONT_MNT_DIR% ^
       --name=%CONT% ^
       --network=%NET% ^
       %IMG%

rem call LOG_EXIT pGO
echo pGO [EXIT]

