@echo off


CALL LOG_LOAD %DIR_BNDL%%CMD_INIT%

CALL %DIR_BNDL%%ENV_DIR%%CMD_INIT%
CALL %DIR_BNDL%%GIT_DIR%%CMD_INIT%
CALL %DIR_BNDL%%LOG_DIR%%CMD_INIT%
CALL %DIR_BNDL%%MISC_DIR%%CMD_INIT%

CALL LOG_UNLOAD %DIR_BNDL%%CMD_INIT%