@echo off


CALL LOG_LOAD %DIR_BNDL%\%FILE_INIT%

CALL %DIR_BNDL%%ENV_DIR%\%FILE_INIT%
CALL %DIR_BNDL%%GIT_DIR%\%FILE_INIT%
CALL %DIR_BNDL%%LOG_DIR%\%FILE_INIT%
CALL %DIR_BNDL%%MISC_DIR%\%FILE_INIT%

CALL LOG_UNLOAD %DIR_BNDL%\%FILE_INIT%