#!/bin/bash
# shellcheck disable=SC2086

source $DIR_BIN$DIR_SLASH"LOG.sh"

log_enter $DIR_BNDL$FILE_INIT

ENV=$DIR_SLASH"env"$DIR_SLASH
FILE_ENV_INIT=$DIR_BNDL$ENV$FILE_INIT
log_var FILE_ENV_INIT $FILE_ENV_INIT
source $FILE_ENV_INIT

GIT=$DIR_SLASH"git"$DIR_SLASH
FILE_GIT_INIT=$DIR_BNDL$GIT$FILE_INIT
log_var FILE_GIT_INIT $FILE_GIT_INIT
source $FILE_GIT_INIT

LOG=$DIR_SLASH"log"$DIR_SLASH
FILE_LOG_INIT=$DIR_BNDL$LOG$FILE_INIT
log_var FILE_LOG_INIT $FILE_LOG_INIT
source $FILE_LOG_INIT

MISC=$DIR_SLASH"misc"$DIR_SLASH
FILE_MISC_INIT=$DIR_BNDL$MISC$FILE_INIT
log_var FILE_MISC_INIT $FILE_MISC_INIT
source $FILE_MISC_INIT


log_exit $DIR_BNDL$FILE_INIT

