#!/bin/bash
# shellcheck disable=SC2086


log_enter $DIR_BNDL$DIR_SLASH$FILE_INIT

export FILE_ENV_INT=$DIR_BNDL$ENV_DIR$DIR_SLASH$FILE_INIT
log_var FILE_ENV_INT $FILE_ENV_INT
source $FILE_ENV_INT

#export FILE_GIT_INT=$DIR_BNDL$GIT_DIR$DIR_SLASH$FILE_INIT
export FILE_GIT_INT=$DIR_BNDL$DIR_SLASH"git"$DIR_SLASH$FILE_INIT
log_var FILE_GIT_INT $FILE_GIT_INT
source $FILE_GIT_INT

export FILE_LOG_INT=$DIR_BNDL$LOG_DIR$DIR_SLASH$FILE_INIT
log_var FILE_LOG_INT $FILE_LOG_INT
source $FILE_LOG_INT

export FILE_MISC_INT=$DIR_BNDL$DIR_SLASH"misc"$DIR_SLASH$FILE_INIT
log_var FILE_MISC_INT $FILE_MISC_INT
source $FILE_MISC_INT


log_exit $DIR_BNDL$DIR_SLASH$FILE_INIT

