#!/bin/bash
# shellcheck disable=SC2086


log_enter $DIR_BNDL$DIR_SLASH$FILE_INIT

source $DIR_BNDL$ENV_DIR$DIR_SLASH$FILE_INIT
source $DIR_BNDL$GIT_DIR$DIR_SLASH$FILE_INIT
source $DIR_BNDL$LOG_DIR$DIR_SLASH$FILE_INIT
source $DIR_BNDL$MISC_DIR$DIR_SLASH$FILE_INIT

log_exit $DIR_BNDL$DIR_SLASH$FILE_INIT

