@echo off


rem call %DIR_BIN%%DIR_SLASH%LOG_ENTER %DIR_GLBL%\openshift%DIR_SLASH%%FILE_INIT%
echo %DIR_GLBL%%DIR_SLASH%os%DIR_SLASH%%FILE_INIT% [ENTER]

rem xcopy /q /y %DIR_GLBL%%DIR_SLASH%openshift%FILES% %DIR_BIN% >NUL

rem call LOG_EXIT %DIR_GLBL%\openshift%DIR_SLASH%%FILE_INIT%
echo %DIR_GLBL%%DIR_SLASH%os%DIR_SLASH%%FILE_INIT% [EXIT]
