@echo off


CALL LOG_ENTER pENV

call sENV
if exist project\pENV (
  call project\pENV
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%OA_SRVR_CONT%"
SET "PROJ_CONT_DATA_DIR=%OA_SRVR_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%OA_SRVR_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%OA_SRVR_CONT_HOME_DIR%"
SET "PROJ_HOST_DIR=%OA_SRVR_HOST_DIR%"
SET "PROJ_IMG=%OA_SRVR_IMG%"
SET "PROJ_PORT_INT=%OA_SRVR_PORT_INT%"
SET "PROJ_VOL=%OA_SRVR_VOL%"
SET "PROJ_VOL_DIR=%OA_SRVR_VOL_DIR%"

CALL LOG_EXIT pENV

