@echo off


  rem CALL LOG_LOAD %DIR_SYS%%DIR_SLASH%%FILE_INIT%
  echo ..%DIR_SLASH%..%DIR_SLASH%system%DIR_SLASH%%FILE_INIT% [ENTER]

  SET "CMD_SRC=..%DIR_SLASH%..%DIR_SLASH%system%ENV_DIR%%DIR_SLASH%%FILE_INIT%"
  ECHO CMD_SRC is %CMD_SRC%
  CALL %CMD_SRC%


  rem CALL LOG_UNLOAD %DIR_SYS%%DIR_SLASH%%FILE_INIT%
  echo ..%DIR_SLASH%..%DIR_SLASH%system%DIR_SLASH%%FILE_INIT% [EXIT]
