#!/bin/bash
# shellcheck disable=SC2086


log_enter $DIR_TMPL_CURR$SYS_DIR$FILE_INIT

TRG=$SYS
log_var TRG $TRG

SRC_MVN=$DIR_SYS$MVN_DIR$FILE_SETTINGS
log_var SRC_MVN $SRC_MVN

cp $SRC_MVN $TRG

SRC_WSDL=$DIR_SYS$SOAP_DIR$FILES_WSDL
log_var SRC_WSDL $SRC_WSDL

cp $SRC_MVN $TRG

log_exit $DIR_TMPL_CURR$SYS_DIR$FILE_INIT