@echo off


call LOG_ENTER pENV

call sENV
if exist project\pENV_MOD (
  call project\pENV_MOD
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_REPO_HOST=%NEXUS_CONT%"
SET "PROJ_REPO_PASSWORD=%NEXUS_PASSWORD%"
SET "PROJ_REPO_PORT=%NEXUS_PORT_EXT%"
SET "PROJ_REPO_USER=%NEXUS_USER%"

SET "PROJ_CONT=%GRDL_LIB_CONT%"
SET "PROJ_CONT_DATA_DIR=%GRDL_LIB_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%GRDL_LIB_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%GRDL_LIB_CONT_HOME_DIR%"
SET "PROJ_HOST_DIR=%GRDL_LIB_HOST_DIR%"
SET "PROJ_IMG=%GRDL_LIB_IMG%"
SET "PROJ_PORT_INT=%GRDL_LIB_PORT_INT%"
SET "PROJ_VOL=%GRDL_LIB_VOL%"
SET "PROJ_VOL_DIR=%GRDL_LIB_VOL_DIR%"

call LOG_EXIT pENV
