@echo off


CALL LOG_ENTER tENV

call sENV
if exist project\pENV_MOD (
  call project\pENV_MOD
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%ANS_CONT%"
SET "PROJ_CONT_DATA_DIR=%ANS_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%ANS_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%ANS_CONT_HOME_DIR%"
SET "PROJ_HOST_DIR=%ANS_HOST_DIR%"
SET "PROJ_IMG=%ANS_IMG%"
SET "PROJ_PORT_INT=%ANS_PORT_INT%"
SET "PROJ_VOL=%ANS_VOL%"
SET "PROJ_VOL_DIR=%ANS_VOL_DIR%"

call LOG_EXIT pENV
