@echo off


CALL LOG_ENTER pENV

call sENV
if exist project\pENV_MOD (
  call project\pENV_MOD
)

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%STASHY_CONT%"
SET "PROJ_CONT_DATA_DIR=%STASHY_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%STASHY_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%STASHY_CONT_HOME_DIR%"
SET "PROJ_HOST_DIR=%STASHY_HOST_DIR%"
SET "PROJ_IMG=%STASHY_IMG%"
SET "PROJ_PORT_INT=%STASHY_PORT_INT%"
SET "PROJ_USER=%STASHY_USER%"
SET "PROJ_VOL_DIR=%STASHY_VOL_DIR%"


CALL LOG_EXIT pENV

